### ISSUE TITLE
feature request: Удалять разрывы строк и переносы

### ISSUE THREAD

**Issue by agapserg** [dimonier/tg2obsidian#10]
Сейчас если боту прислать сообщение вида:
```
Привет
Сходи за хлебом
Купи еще сметану 
А еще яйца
```
То он сохранит всё это в заметку так же с переносами строк.
А хотелось бы иметь возможность например в конфиге проставить параметр "ВсегдаБезПереносов" и в конечном итоге получить текст вот такого вида: 
`Привет Сходи за хлебом Купи еще сметану А еще яйца`

**Comment by mikkovedru** [comment]
Опиши пожалуйста сценарий использования. А то со стороны выглядит как очень узконаправленное желание типа "сделайте так чтобы все пробелы удалялись и текст шел одним потоком `ПриветСходизахлебомКупиещесметануАещеяйца`". Т.е. может это и полезно, но на первый взгляд непонятно почему. И где тут лежит достаточно профита чтобы и этот функционал программировать и усложнять код и использование программы для всех других пользователей?

**Comment by agapserg** [comment]
Я использую связку обсидиан + бот так:
1. Появляется мысль\задача\ссылка => Я пишу её в телегу в группу бота. 
- Мысль может возникнуть спонтанно, важно её не упустить и записать в первозданном виде
- Обсидиан не всегда под рукой и открывается дольше чем телега
- Т.к. основной мессенджер у меня - это телега, то часто новые вводные и задачи приходят там
- Благодаря боту легко осуществить трансфер задачи\вводной из телеги в телегу

2. Некая запись падает в обсидиан и там лежит до ежедневного разобра инокса

3. Я немного адаптировал бота под себя и у меня заметки пишутся всегда в один файл INBOX 
- Это удобнее для меня поскольку во время ежедневного разбора инбокса мне не нужно бегать по разным файлам от разных дат 
- Логика в  процессе такая - если в заметке INBOX есть строчки - значит надо доразобрать 
- Иными словами один INBOX как входящие в почтовом клиенте
- Стандартная же логика бота немного иная - он складывает весь текст в разные заметки по датам
- В моей логике текст скинутый ботом не долгое время хранится в инбоксе, а потом перекидывается в нужный проект, т.е. в другую заметку
- В логике заложенной в бота изначально видимо текст продолжит хранится в разных заметках от разных дат

4. Каждая строчка в инбоксе у меня имеет вид: ГГГГ-ММ-ДД - Текст заметки 
- Это я тоже сам под себя скорректировал код бота

5. Ежедневный обзор
- Я иду в файл INBOX и начинаю разбирать его сверху вниз
- Каждую строчку начинаю сортировать в разные проекты
- У меня забинден хоткей на выделение всей строчки и перемещение в другую заметку
- Т.е. я нажимаю например на ALT + E - выделяю строчку
- Затем нажимаю на ALT + R - и перемещаю выделенную строчку в нужный мне проект

6. Почему нужно в одну строчку
- При таком сценарии использования многострочные заметки (пример я привёл про список покупок в самом первом сообщении в этой ветке) нужно дополнительно выделять построчно, что немного увеличивает количество кликов 
- Если же реализовать ту функцию, что я прошу, то будет сохранятся следующее правило: "Одна заметка = одна строчка" и я легко смогу сортировать заметки в инбоксе двумя кликами вместо N-ого количества кликов.

p.s.
@mikkovedru Я прошу не пробелы удалять, а переносы и разрывы строк.
Посмотрите внимательнее на ваш пример и мой пример, вы как-будто бы считаете, что я хочу удалять из заметки пробелы, но речь не о них, а о переносах строк и разрывах, т.е. "\n"

**Comment by dimonier** [comment]
@agapserg спасибо!

К данному вопросу не относится, но поскольку речь зашла, хочу прокомментировать эти строки:

> В логике заложенной в бота изначально видимо текст продолжит хранится в разных заметках от разных дат
> Каждая строчка в инбоксе у меня имеет вид: ГГГГ-ММ-ДД - Текст заметки
> Это я тоже сам под себя скорректировал код бота

В бота тоже заложена логика инбокса, который должен регулярно очищаться.
Просто у вас заметки однострочные, и вы маркируете их датой в начале строки. А в боте сейчас для удобства разбора заметок, скопившихся за несколько дней, заметки сгруппированы в разных файлах - по одному на каждый день. Ну просто я делал исходя их своих личных предпочтений :)

- Всё складывать в один файл уже тоже можно, если закомментировать параметр `note_date = True` или установить `note_date = False`
- Для вставки отметки даты-времени в начало строки вместо заголовка #### могу сделать параметр в конфиге, если это будет востребовано.

**Comment by agapserg** [comment]
Ну в вашей логике у вас несколько инбоксов, а в моем варианте один. 
При чистке инбокса состоящего из нескольких файлов - надо будет потом еще и файлы удалять или проверять, чищенные ли они или нет, я не понимаю зачем плодить много инбоксов, но это как кто привык, ваш сценарий чистки инбоксов может отличаться от моего, кто как хочет так и ...
Я по методу GTD Дэвида Аллена юзаю один инбокс, если там есть хоть одна строчка - для меня это сигнал, что инбокс надо чистить, даже не представляю, во что бы превратилась чистка инбокса с несколькми файлами: "Ой так, я за вчера инбокс почистил? А за позавчера? А за 31 декабря?"

Я не настаиваю на реализации этой фичи, если руки дойдут я сам допишу код.

p.s.
К слову, я попытался юзать бота на дефолтных настройках с сортировкой в разные файлы - нет, спасибо, мне не удобно.

**Comment by dimonier** [comment]
@agapserg Готово, см. параметр one_line_note в config.py

**Comment by agapserg** [comment]
Видимо не выгрузили изменения, нет что-то такого параметра:
![image](https://user-images.githubusercontent.com/70086148/212620249-3214b229-3d2f-4165-bfe6-b2e9399aad00.png)

**Comment by dimonier** [comment]
> Видимо не выгрузили изменения, нет что-то такого параметра

@agapserg Прошу прощения, push не долетел.
Теперь всё на месте.

**Comment by mikkovedru** [comment]
Фича сделана, но я всё равно прокомментирую некоторые моменты.
@agapserg 
> * Т.е. я нажимаю например на ALT + E - выделяю строчку
> * Затем нажимаю на ALT + R - и перемещаю выделенную строчку в нужный мне проект

Я не знаю какую конкретно функцию ты используешь, но если Extract current selection, то непонятно что мешает просто выделить нужные строчки и переместить все эти строчки одновременно в нужное место.

Разбираться в task-ах намного легче если они написаны на отдельных строках, а не все вместе. Всё вместе неудобно даже если речь даже об одном типе задач типа покупок в магазине (тем более если не ставить точек и знаков препинания, не пользоваться шифтом и вообще получить сливающиеся слова). Если же задачи разного типа, да в перемешку, то выглядит крайне неудобно.


> Я по методу GTD Дэвида Аллена юзаю один инбокс, если там есть хоть одна строчка - для меня это сигнал, что инбокс надо чистить, даже не представляю, во что бы превратилась чистка инбокса с несколькми файлами: "Ой так, я за вчера инбокс почистил? А за позавчера? А за 31 декабря?"

Я сам гтдшник. Просто по разному организованы процессы:
- У тебя всё сваливается в одно место и тебе надо обязательно его разбирать, даже если большинство не является actionable, а просто идет в архив. Но всё равно добавляют стресса.
- У @dimonier "дневные файлы" не требуют обязательной разборки. Для тасков вообще лучше использовать отдельные программы типа todoist. Так что в основном в Обсидиан идет то, что даже после разбора будет квалифицироваться в архив. И нынешняя организация позволяет, если есть время и необходимость, эти записи обрабатывать и организовывать в отдельные записи. Но также позволяет никак их особо не обрабатывать, никак на них не тратить время, усилия и нервы. Но при этом вся информация сохранена, сделана удобно (не огромным одним файлом, а многими; т.е. позволяет смотреть на прогресс темы и историю), и, когда надо, найдется.
