### ISSUE TITLE
OCR text recognition from images

### ISSUE THREAD

**Issue by mikkovedru** [dimonier/tg2obsidian#13]
We already have voice recognition from audio messages.

It would also be useful to have text in images automatically recognized.

Does anyone know any good free OCR libraries?

**Comment by dimonier** [comment]
@mikkovedru  I've heard about an OCR module for Python, but... do you really have such a necessity?

**Comment by mikkovedru** [comment]
@dimonier 
Yes. I save a lot of images (memes, screenshots with quotes, screenshots of messages, screenshots of articles) with text in them and would like to search that text (however imperfect the recognition).

I researched options and it seems that https://github.com/tesseract-ocr/tesseract is the way to go.

An example library: 
- https://pypi.org/project/pytesseract/
- https://www.geeksforgeeks.org/text-localization-detection-and-recognition-using-pytesseract/
Seems easy enough.

**Comment by dimonier** [comment]
@mikkovedru basically OCR works in dev mode for ruan + eng.
You can install https://github.com/tesseract-ocr/tessdoc and check out script version with OCR at https://github.com/dimonier/tg2obsidian/tree/13-ocr-text-recognition-from-images

Please let me know how it works for you if you still interested in this feature
