### ISSUE TITLE
Кроссплатформенность проекта

### ISSUE THREAD

**Issue by Pushkin31** [dimonier/tg2obsidian#21]
Здравствуйте!
Проект очень полезный и явно найдет своего пользователя. Спасибо Вам за работу!

Такой вопрос: планируется ли образ docker и docker-compose? 
Чтоб крутить бота не на своей системе windows (хотя я больше использую linux), но можно было крутить и на серверах, vds да и на чем угодно (говоря про докер).
Хотел собрать докер-компос, но завис на зависимостях:
как минимум 
```
kivy-deps.angle
kivy-deps.glew
kivy-deps.sdl2
pywin32
pywin32-ctypes
py-win-keyboard-layout
```
есть только на вин, поэтому сразу всё отпадает...

Ладно образ, но просто возможность запускать на linux...

**Comment by pkb** [comment]
@Pushkin31
> Ладно образ, но просто возможность запускать на linux...

На линуксе оно запускается, все зависимости перечислены в readme, никаких специфичных для win нет.

**Comment by dimonier** [comment]
> Проект очень полезный и явно найдет своего пользователя. Спасибо Вам за работу!
> 
> Такой вопрос: планируется ли образ docker и docker-compose?

Спасибо за спасибо :)

Темами docker и docker-compose пока не владею, к сожалению.
Если / когда освою, тогда, может быть появится и образ.
