### ISSUE TITLE
после отправки поста, содержащий эмодзи - меняется кодировка документа

### ISSUE THREAD

**Issue by Pushkin31** [dimonier/tg2obsidian#22]
Сначала отправляю пару текстовых сообщений (на русском языке). Отображается всё отлично и заносится в документ.
Следует мне переслать пост, содержащий картинку, гиперссылку и эмодзи - кодировка всего документа меняется.
С постами без эмодзи - всё ок.

Вот до отправки поста

<details>
<summary>скрин</summary>

![image](https://github.com/dimonier/tg2obsidian/assets/35974828/ce23633a-415d-4965-83d8-d0a62e49b159)

</details>

После

<details>
<summary>скрин</summary>

![image](https://github.com/dimonier/tg2obsidian/assets/35974828/db41a8f0-3c75-4386-8f1f-d2215052107e)

</details>

Пост выглядит следующим образом:
[ссылка на пост](https://t.me/typicalvoronezh/10890)

<details>
<summary>скрин</summary>

![image](https://github.com/dimonier/tg2obsidian/assets/35974828/fe8b5689-ac9d-478e-b146-fde01be7437f)

</details>

Прошу проверить баг с эмозди анимированными и без анимации.

система:
ubuntu 22.04
5.15.0-71-generic
VDS

**Comment by pkb** [comment]
@Pushkin31 приложите md файл, демонстрирующий проблему с кодировкой.

**Comment by Pushkin31** [comment]
> @Pushkin31 приложите md файл, демонстрирующий проблему с кодировкой.

@pkb 
приложил

[Telegram-2023-05-28_Notes.md](https://github.com/dimonier/tg2obsidian/files/11593978/Telegram-2023-05-28_Notes.md)

**Comment by pkb** [comment]
@Pushkin31 я не вижу проблем с этим файлом - это валидный utf8 (как и должно быть), без проблем отображается в obsidian ❗️🔥

**Comment by Pushkin31** [comment]
> @Pushkin31 я не вижу проблем с этим файлом - это валидный utf8 (как и должно быть), без проблем отображается в obsidian ❗️🔥

У меня есть необходимость для открытия некоторых заметок через блокнот. Через блокнот, после репоста с аним эмодзи – не читается документ.
До репоста – все читается.

Причем не читается только то, что на русском. Англ отображается нормально.

**Comment by pkb** [comment]
А что за блокнот? Стандартный виндовый блокнот у меня читает без проблем. Из всех софтин, что я попробовал с этим файлом только Notepad++ глючит. То, что с русским проблемы, это понятно, в utf8 младшие символы совпадают с ascii т.е. с англ. никогда проблем не будет.

**Comment by Pushkin31** [comment]
> А что за блокнот? Стандартный виндовый блокнот у меня читает без проблем. Из всех софтин, что я попробовал с этим файлом только Notepad++ глючит. То, что с русским проблемы, это понятно, в utf8 младшие символы совпадают с ascii т.е. с англ. никогда проблем не будет.

Блокноты, с которыми работаю:
notepad++, встроенный блокнот в mobaxterm
Вчера не смог проверить, но есть предположение, что на лине geany тоже так же будет открывать 

Upd: geany открывает нормально

**Comment by dimonier** [comment]
@Pushkin31 дело не в файле, дело в способности вашего блокнота автоматически определять кодировку.
В первом случае она работает, и кодировка UTF-8 определяется и отображается нормально, а во втором (после добавление эмодзи) почему-то перестаёт, и блокнот показывает файл, как будто он в кодировке ANSI.
