### ISSUE TITLE
После распознавания гс бот занимает 3гб оперативки в фоне.

### ISSUE THREAD

**Issue by Jly4** [dimonier/tg2obsidian#24]
Все было хорошо до установки PyTorch, хотел чтобы использовалась видеокарта, но появился такой неприятный момент. Планировал держать бота включенным в фоне, но если он будет постоянно занимать столько оперативки будет не приятно. Пока поставил распознование принудительно на процессоре.
![image](https://github.com/dimonier/tg2obsidian/assets/65804380/81c00bd6-835b-4f64-99e4-4ddbfe8691a0)

**Comment by dimonier** [comment]
В коде прописано освобождение памяти после распознавания. Так что память должна бы очищаться.
Для удобства в новой версии дал возможность указывать устройство для распонавания речи в конфиге: cuda или cpu.

У себя полностью перевёл бота на cpu, т.к. cuda используется для других целей, а на коротких фрагментах речи разница по времени распознавания не существенна.
