### ISSUE TITLE
Проблемы с AIOgram

### ISSUE THREAD

**Issue by chieftain-yu** [dimonier/tg2obsidian#27]
Пытаюсь развернуть бота у себя.
Столкнулся с тем, что aiogram обновил версию (с 2 на 3 - и предпринял ряд изменений), и теперь tg2obsidian_bot.py жалуется:
C:\(путь)\tg2obsidian-main>python tg2obsidian_bot.py
Traceback (most recent call last):
  File "C:\(путь)\tg2obsidian-main\tg2obsidian_bot.py", line 18, in <module>
    from aiogram.dispatcher.filters.builtin import CommandStart, CommandHelp
ModuleNotFoundError: No module named 'aiogram.dispatcher.filters'

Есть ли у вас в планах обновление бота под актуальную версию aiogram?

**Comment by dimonier** [comment]
Да, переработка под aiogram 3 в процессе

**Comment by chieftain-yu** [comment]
Надеюсь, не очень вас обижу известием, что сделал форк (пока чисто локальный), и теперь тоже немножко навожу марафет?

**Comment by dimonier** [comment]
Конечно, наводите! Я же выложил код, чтобы он приносил пользу всем желающим :)

**Comment by icewind666** [comment]
Для тех кто временно ищет фикс и пришел сюда - можно понизить версии aiogram 
pip install aiogram==2.25.2

**Comment by dimonier** [comment]
Выпущена версия бота на aiogram 3: https://github.com/dimonier/tg2obsidian/releases/tag/v1.0.0
