### ISSUE TITLE
feature request: Добавить параметр в конфиг "Не хранить логи" или "Срок хранения логов"

### ISSUE THREAD

**Issue by agapserg** [dimonier/tg2obsidian#5]
Мой опыт говорит о том, что неконтролируемые логи - это плохая практика.
Они потом разрастаются до неимоверных размеров, утекают куда не нужно и т.д.

Предлагаю в конфиге сделать параметр, который позволит включать или выключать логирование.

На крайний случай можно сделать параметр, которым можно задавать срок жизни логов в днях. 
Например если выставить параметр равным 1 день, то каждый день некая процедура будет проверять логи и все файлы старше 1 дня будут удаляться.

**Comment by dimonier** [comment]
@agapserg Вы имеете в виду файлы вида messages-2023-01-11.txt или bot.log?
Или и то, и другое?

**Comment by agapserg** [comment]
@dimonier и то и другое.

**Comment by dimonier** [comment]
@agapserg готово, см. параметр log_level в config.py
