### ISSUE TITLE
feature request: Не выделять ничего жирным текстом

### ISSUE THREAD

**Issue by agapserg** [dimonier/tg2obsidian#6]
Сейчас в коде есть вот такая строчка №187
` result = f'**Forwarded {forward_info}**\n'`

Вот при сохранении заметки из-за этой строчки часть текста выделяется жирным.

Конечно не сложно каждый раз при обновлении бота удалять из этой строчки звёздочки, но чтоб приблизить бота к совершенству можно было бы в конфиге сделать параметр "Выделять жирным Forwarded" и чтобы каждый для себя мог это настроить.

**Comment by dimonier** [comment]
@agapserg А если в тексте пересланной заметки было форматирование, то что с ним должно происходить, когда форматирование отключено?

**Comment by mikkovedru** [comment]
В конфиге есть опция `format_messages` если форматирование текста не нужно.

**Без дополнительной аргументации** не вижу целесообразным делать опции и программировать логику для каждого типа сообщений и для каждого типа форматирования отдельно.

**Comment by agapserg** [comment]
@dimonier на мой взгляд можно привязать выделение жирным текста Forwarded from к параметру форматирования, который уже есть в конфиге, т.е 
format_messages = True - всё выделяется жирным и формат сохраняется изначального сообщения
format_messages = False - ничего вообще не выделяется жирным и формат изначального сообщения не сохраняется тоже

На мой взгляд такая логика должна быть.

Так же на мой взгляд подобного ценность бота подобного рода в его максимальной кастомизации минимальными усилиями.
Т.е. 100 настраиваемых параметров лучше 5 настраеваемых параметров.
Это IT-гиганты типа Apple или Google делают минимальное кол-во настроек в своём софте, для красивости и лаконичности.
А в таком проекте как бот, который записывает текст в файлы, чем больше настроек изначально тем лучше, тем больше людей смогут его использовать и настроить под себя "из коробки".

P.s.
Если вы не видите в этом логики и смысла и чего-то еще - то закрывайте Issue, я как-нибудь сам перебьюсь.

**Comment by dimonier** [comment]
> можно привязать выделение жирным текста Forwarded from к параметру форматирования, который уже есть в конфиге, т.е
> format_messages = True - всё выделяется жирным и формат сохраняется изначального сообщения
> format_messages = False - ничего вообще не выделяется жирным и формат изначального сообщения не сохраняется тоже

Так и сделаю

**Comment by dimonier** [comment]
@agapserg готово
