### ISSUE TITLE
feature request: Нейминг файлов

### ISSUE THREAD

**Issue by agapserg** [dimonier/tg2obsidian#7]
Названия картинок когда сохраняются в хранилище имеют название fsdkjfhwkehvjsfk.
Я так понимаю, что подобные названия присваивает телеграм.

Идея в том, чтобы их как-нибудь попытаться упорядочить, например "2023-01-10 - %Название канала% - %Рандомное 2х значое число%".

Таким образом в хранилище обсидиан будет больше порядка, а не куча файлов вида "fsdfkjsdfkjsdlkfjdslf"

Формат ГГГГ-ММ-ДД - выбран не случайно, т.к. все файлы в т.ч. в обсидиане по умолчанию фильтруются по названию и таким образом будет обеспечен еще дополнительный порядок - сверху самые древние файлы, снизу - самые свежие.

**Comment by mikkovedru** [comment]
Предлагаю формат:
`YYYY-MM-DD_[название-основной-записи-без-даты-и-без-обрамляющих-тире-и-андерскоров]_pic[порядковый-номер).расширение`

Т.е. у файла `Telegram-2023-01-02_Notes.md` были бы графические файлы:
- `2023-01-02_Telegram-Notes_pic1.jpg`
- `2023-01-02_Telegram-Notes_pic2.png`

А ежедневные файлы `messages-YYYY-MM-DD.txt` имели бы название графических файлов:
- `2023-01-11_messages_pic1.jpg` и т.д.

**Comment by dimonier** [comment]
@mikkovedru не понял в конце про *.txt. Это вспомогательные файлы для отладки, картинки с ними не связаны.

**Comment by dimonier** [comment]
Сделал так:
- Для первой картинки: `YYYY-MM-DD_[название-основной-записи-без-даты-и-без-обрамляющих-тире-и-андерскоров]_pic.jpg`
- Для второй картинки и далее: `YYYY-MM-DD_[название-основной-записи-без-даты-и-без-обрамляющих-тире-и-андерскоров]_pic_[порядковый-номер-начиная-с-1].jpg`

Т.е.:
- 2023-01-11_Telegram-Notes_pic.jpg
- 2023-01-11_Telegram-Notes_pic_1.jpg
- 2023-01-11_Telegram-Notes_pic_2.jpg
- ...

**Comment by mikkovedru** [comment]
Андерскор между `pic` и номером - это ок. Можно с ним, а можно без него.

А вот то что первая картинка идет без номера, а вторая картинка имеет номер один - это плохо. Я вопросами нейминга файлов занимаюсь 20 лет и это то, к чему я пришел после десятилетий раздумывания. Поэтому предлагаю начинать именование картинок сразу с первого номера, даже если картинка лишь одна. Если тебе лень, то я могу сделать PR. Там элементарно.

**Comment by agapserg** [comment]
Про нейминг 1,2,3,4
- Я бы еще добавил 0 в начало номеров до 9 включительно 
- Т.е. 01, 02, 03, ...., 10, 11
- Таким образом не будут перемешиваться файлы с номером 1 и номером 10
- В варианте без нуля файлы с номером 1 и номером 10 будут стоять рядом, а файлы 2, 3, 4 будут идти после 10

**Comment by dimonier** [comment]
@mikkovedru @agapserg уговорили. Сделал так:

> * 2023-01-11_Telegram-Notes_pic01.jpg
> * 2023-01-11_Telegram-Notes_pic02.jpg
> * 2023-01-11_Telegram-Notes_pic03.jpg
> * ...
